# Permalinks
permalink:	pretty

# Setup
title:	Waqas Ahmed
tagline:	My opinions and inspirations
description:	Trying to get my head around it.
url:	https://waqas.dev/
markdown: kramdown
highlighter: rouge

author:
  name:	Waqas Ahmed
  email: mail@waqas.dev
  url:	https://twitter.com/uberbinge

paginate:	3

# Custom vars
version:	1.0.0

github:
  repo: https://github.com/waah42/waah42.github.io

pages_list:       
  About:	'/about'
  Posts:	'/posts'
  Feed:	'/atom.xml'

# gems
gems: [jekyll-paginate]
